/**
 * Bidirectional text, UAX #9 (spec 02 §6.3, task 8): the full P/X/W/N/I/L rule set, BD16
 * paired-bracket resolution (N0) and BD14/BD15 mirroring — everything Fadewright's Hebrew
 * and Arabic RTL templates need to lay out correctly.
 *
 * **Bidi_Class canonicalization (a Task 6 finding, worked around here).** `bidiClass(cp)`
 * (`./ucd.generated.js`, generated by `scripts/build-ucd.ts` from `DerivedBidiClass.txt`)
 * returns *two different spellings for the same abstract value* depending on whether `cp`
 * falls in an explicit data line or an `@missing` default range: explicit ranges spell the
 * short alias (`'L'`, `'R'`, `'AL'`, `'ET'`, ...) but the file's four `@missing` defaults
 * spell the long alias (`'Left_To_Right'`, `'Right_To_Left'`, `'Arabic_Letter'`,
 * `'European_Terminator'`) — verified against `scratch/ucd/DerivedBidiClass.txt`'s own
 * `@missing:` lines. `BIDI_CLASS_NAMES` bakes both spellings in as distinct enum members, so
 * `bidiClass(cp) === 'R'` silently returns `false` for an *unassigned* code point in, say,
 * the Hebrew block (0590..05FF defaults to `Right_To_Left`, not `R`) even though it is a
 * Right_To_Left code point. This is a real latent bug in the shared Task 6 getter, not
 * something introduced here — flagged in the task 8 report rather than fixed at the
 * generator (regenerating touches Task 6/7's already-reviewed, already-committed output and
 * their conformance re-runs, which is out of this task's scope). `classOf` below normalizes
 * both spellings to the canonical short form before this module does anything with them, so
 * every comparison in this file is safe regardless of which spelling `bidiClass` returned.
 *
 * **Algorithm shape.** UAX #9, run per paragraph (one call = one paragraph; a document's own
 * paragraph splitting is the caller's job — B, the paragraph separator, is handled per X8 but
 * both official conformance files guarantee it appears at most once, as the last character):
 *   1. **P2/P3** (`resolveParagraphLevel`) — first strong character, skipping isolate
 *      contents; `'auto'` only, `'ltr'`/`'rtl'` short-circuit, no strong character falls back
 *      to the caller's `fallback` (spec 02 §6.3: "an empty paragraph inherits the document
 *      direction").
 *   2. **X1–X8** (`computeExplicitLevels`) — the directional status stack, producing an
 *      embedding level and a (possibly override-reset) type for every code point, including
 *      the explicit-formatting and isolate characters X9 will later remove.
 *   3. **X9** (`survivingIndices`) — RLE/LRE/RLO/LRO/PDF/BN are removed from further
 *      processing (not from the output array: `bidiLevels` still returns one entry per code
 *      point). Isolate initiators and PDI are *not* removed.
 *   4. **BD7 + BD13** (`buildIsolatingRunSequences`) — group the surviving code points into
 *      level runs, then chain level runs connected by a matching isolate-initiator/PDI pair
 *      into isolating run sequences, each with its own sos/eos (X10).
 *   5. **W1–W7, N0, N1–N2, I1–I2** run per isolating run sequence, left to right, each a full
 *      pass over that sequence before the next rule starts (matching the spec's own
 *      rule-at-a-time definition, not a fused single scan — several rules read a
 *      already-updated neighbour's type from *this* pass, e.g. W1's "type of previous
 *      character").
 *   6. **N0 / BD16** (`resolveBrackets`) identifies paired brackets (a stack of open
 *      brackets, ≤63 deep per BD16, canonically equating U+2329/U+3008 and U+232A/U+3009 —
 *      verified against `BidiCharacterTest.txt` lines 311–318, which mix the two spellings
 *      in one pair) and assigns both brackets in a pair the embedding direction, the opposite
 *      direction (if that direction has established context before the pair), or leaves them
 *      neutral (if nothing strong is enclosed) — sequentially in opening-bracket order, so a
 *      later pair's scan sees an earlier pair's already-resolved type. **`resyncNonspacingMarks`**
 *      then re-syncs each NSM to its immediately preceding position's *final* type: strict W1
 *      makes an NSM inherit its base's type as a snapshot *before* N0 runs, but
 *      `BidiCharacterTest.txt` lines 84–89/103/109/114 (an NSM immediately after a bracket
 *      that N0 itself resolved) show the official data expects the NSM to track the base's
 *      *final* resolved type instead — a real, empirically-found interaction between W1 and
 *      N0 the literal rule order doesn't make obvious; see `resyncNonspacingMarks`'s own
 *      comment and the task 8 report.
 *   7. **L1** (`applyL1Reset`) resets segment/paragraph separators unconditionally and
 *      whitespace/isolate-formatting runs before a separator or at text end, using the
 *      *original* (pre-X6-override, pre-W/N/I) types, per L1's own "original types, not
 *      those modified by previous phases" — and treating X9-removed characters (BN and the
 *      explicit-formatting classes) as transparent to "before a separator"/"at text end"
 *      rather than as stopping points: `BidiTest.txt` line 2476 (`LRE WS LRE; 3`,
 *      `@Levels: x 0 x`) proves this — the WS is followed only by a removed LRE, so once
 *      removed characters are looked through it genuinely is at the end of the line. **Scope
 *      note:** both official conformance files state their L1/L2 assume "all characters...
 *      rendered on a single line" (`BidiTest.txt` header) — `bidiLevels` matches that and
 *      treats the whole paragraph as one line, since it has no line-break information. A
 *      caller that breaks a paragraph into multiple lines must re-apply L1's end-of-line
 *      reset per line itself before calling `reorderVisual` (which is pure L2, given only
 *      levels and a range — no character classes to re-derive L1 from). This is a Task 8
 *      scope boundary, not an oversight; flagged in the report.
 *   8. **L2** (`reorderVisual`) — reverse contiguous same-level-or-higher runs from the
 *      highest level down to the lowest odd level, within `[start, end)`.
 *   9. **Mirroring** (`mirrorChar`, BD14/BD15/`BidiMirroring.txt`) is level-agnostic: the
 *      caller applies it only to characters whose *resolved* level is odd, at display-text
 *      generation (spec 02 §6.3) — this module doesn't know which characters end up in an
 *      RTL run until the caller has both `bidiLevels` and the visual order.
 *
 * **Indexing.** `bidiLevels`/`reorderVisual` work in **code-point** units (one array entry
 * per Unicode code point, astral characters counted once), matching both conformance files'
 * own indexing (`BidiCharacterTest.txt`'s field 4 is "indices... into the input string" where
 * the input string is itself a space-separated list of code points) — not UTF-16 code units,
 * unlike `grapheme.ts`/`linebreak.ts`'s offset arrays. A caller bridging this module's output
 * against a UTF-16-offset-based break array needs its own code-point/UTF-16 index map; that
 * bridge is a later task's concern, not this module's.
 *
 * **Performance (spec 02 §33/§08 §15, task 8 brief note 5).** Most screenplay paragraphs are
 * pure LTR. `bidiLevels` proves and takes a fast path: with `paragraphLevel === 0` (LTR) and
 * no code point of class R, AL, AN, or any explicit-formatting/isolate class present, W7
 * unconditionally turns every EN into L (its backward strong-type search only ever finds L or
 * sos=L, since R/AL never appear to interrupt it — AN is untouched by W7, hence AN's own
 * exclusion from the fast path), every neutral resolves to L by N1/N2 (uniform L context on
 * both sides), and I1 (even level) then gives every code point level `paragraphLevel` (0) —
 * so the whole pipeline is skippable, returning an all-zero array in one O(n) scan.
 */
import { BIDI_CLASS_NAMES, BIDI_CLASS_STARTS, BIDI_CLASS_VALUES } from './generated/bidi-class.generated.js';
import { BIDI_BRACKET_CODES, BIDI_BRACKET_PAIRED, BIDI_BRACKET_TYPES } from './generated/bidi-brackets.generated.js';
import { BIDI_MIRROR_CODES, BIDI_MIRROR_MAPPED } from './generated/bidi-mirroring.generated.js';
import { exactIndex, lookupRangeValue } from './ucd-lookup.js';

// ─── Bidi_Class, canonicalized (see header comment) ────────────────────────────────────────

type Cls =
  | 'L' | 'R' | 'AL' | 'EN' | 'ES' | 'ET' | 'AN' | 'CS' | 'NSM' | 'BN' | 'B' | 'S' | 'WS' | 'ON'
  | 'LRE' | 'LRO' | 'RLE' | 'RLO' | 'PDF' | 'LRI' | 'RLI' | 'FSI' | 'PDI';

/** The four `@missing`-default long-form spellings `DerivedBidiClass.txt` emits, mapped to their short alias. */
const LONG_ALIAS: Readonly<Record<string, Cls>> = {
  Left_To_Right: 'L',
  Right_To_Left: 'R',
  Arabic_Letter: 'AL',
  European_Terminator: 'ET',
};

function classOf(cp: number): Cls {
  const raw = BIDI_CLASS_NAMES[lookupRangeValue(BIDI_CLASS_STARTS, BIDI_CLASS_VALUES, cp)] ?? 'Left_To_Right';
  return (LONG_ALIAS[raw] ?? raw) as Cls;
}

// ─── Decoding (code-point granularity — see header comment) ───────────────────────────────

interface CodePointAt {
  cp: number;
  index: number; // UTF-16 offset, kept only for reference/debugging — the level arrays this module returns are code-point indexed.
}

function decode(text: string): CodePointAt[] {
  const out: CodePointAt[] = [];
  let i = 0;
  while (i < text.length) {
    const cp = text.codePointAt(i);
    if (cp === undefined) break;
    out.push({ cp, index: i });
    i += cp > 0xffff ? 2 : 1;
  }
  return out;
}

// ─── P2/P3: paragraph level ────────────────────────────────────────────────────────────────

const ISOLATE_INITIATORS: ReadonlySet<Cls> = new Set(['LRI', 'RLI', 'FSI']);

/**
 * P2/P3 (spec 02 §6.3): the first strong (L/R/AL) character, skipping over the whole content
 * of any isolate (an isolate initiator's content, up to its matching PDI or the end of the
 * scanned range, is invisible to this scan — per P2's own "an isolate initiator, along with
 * its matching PDI... is skipped over"). Task 8 brief's exact interface.
 */
export function resolveParagraphLevel(text: string, override: 'auto' | 'ltr' | 'rtl', fallback: 0 | 1): 0 | 1 {
  if (override === 'ltr') return 0;
  if (override === 'rtl') return 1;
  const types = decode(text).map((c) => classOf(c.cp));
  const rtl = firstStrongIsRTL(types, 0, types.length);
  if (rtl === undefined) return fallback;
  return rtl ? 1 : 0;
}

/**
 * P2/P3's scan, reused by X5c (an FSI resolves to RLI/LRI by running this over its own
 * content). Returns `true` (RTL), `false` (LTR), or `undefined` (no strong character found —
 * P3's own default is LTR, but the two call sites handle "not found" differently: P2/P3
 * proper falls back to the caller's document direction, X5c defaults to LRI/LTR).
 */
function firstStrongIsRTL(types: Cls[], start: number, end: number): boolean | undefined {
  let isolateDepth = 0;
  const limit = Math.min(end, types.length);
  for (let i = start; i < limit; i++) {
    const cls = types[i] as Cls;
    if (ISOLATE_INITIATORS.has(cls)) {
      isolateDepth++;
      continue;
    }
    if (cls === 'PDI') {
      if (isolateDepth > 0) isolateDepth--;
      continue;
    }
    if (isolateDepth > 0) continue;
    if (cls === 'L') return false;
    if (cls === 'R' || cls === 'AL') return true;
  }
  return undefined;
}

// ─── X1–X8: explicit levels ─────────────────────────────────────────────────────────────────

const MAX_DEPTH = 125;

interface StackEntry {
  level: number;
  override: 'N' | 'L' | 'R';
  isolate: boolean;
}

function nextLevel(level: number, rtl: boolean): number {
  if (rtl) return level % 2 === 0 ? level + 1 : level + 2;
  return level % 2 === 1 ? level + 1 : level + 2;
}

/** BD9: matches each isolate initiator with its PDI, structurally — independent of X-rule overflow bookkeeping. */
function computeMatchingPDI(types: Cls[]): (number | undefined)[] {
  const n = types.length;
  const match: (number | undefined)[] = new Array(n).fill(undefined);
  const stack: number[] = [];
  for (let i = 0; i < n; i++) {
    const t = types[i] as Cls;
    if (ISOLATE_INITIATORS.has(t)) stack.push(i);
    else if (t === 'PDI' && stack.length > 0) {
      const j = stack.pop() as number;
      match[j] = i;
      match[i] = j;
    }
  }
  return match;
}

/** X1–X8: the directional status stack. `types` is mutated in place for X6/X5a/X5b/X6a's override resets; the return is `levels` only (callers already hold the mutated `types`). */
function computeExplicitLevels(codeTypes: Cls[], types: Cls[], paragraphLevel: 0 | 1, matchingPDI: (number | undefined)[]): Uint8Array {
  const n = types.length;
  const levels = new Uint8Array(n);
  const stack: StackEntry[] = [{ level: paragraphLevel, override: 'N', isolate: false }];
  let overflowIsolateCount = 0;
  let overflowEmbeddingCount = 0;
  let validIsolateCount = 0;
  const top = (): StackEntry => stack[stack.length - 1] as StackEntry;

  for (let i = 0; i < n; i++) {
    const t = types[i] as Cls;
    switch (t) {
      case 'RLE':
      case 'LRE':
      case 'RLO':
      case 'LRO': {
        const cur = top();
        levels[i] = cur.level;
        const isRTL = t === 'RLE' || t === 'RLO';
        const newLevel = nextLevel(cur.level, isRTL);
        if (newLevel <= MAX_DEPTH && overflowIsolateCount === 0 && overflowEmbeddingCount === 0) {
          stack.push({ level: newLevel, override: t === 'RLO' ? 'R' : t === 'LRO' ? 'L' : 'N', isolate: false });
        } else if (overflowIsolateCount === 0) {
          overflowEmbeddingCount++;
        }
        break;
      }
      case 'RLI':
      case 'LRI':
      case 'FSI': {
        let isRTL = t === 'RLI';
        if (t === 'FSI') isRTL = firstStrongIsRTL(codeTypes, i + 1, matchingPDI[i] ?? n) === true;
        const cur = top();
        levels[i] = cur.level;
        if (cur.override !== 'N') types[i] = cur.override;
        const newLevel = nextLevel(cur.level, isRTL);
        if (newLevel <= MAX_DEPTH && overflowIsolateCount === 0 && overflowEmbeddingCount === 0) {
          validIsolateCount++;
          stack.push({ level: newLevel, override: 'N', isolate: true });
        } else {
          overflowIsolateCount++;
        }
        break;
      }
      case 'PDI': {
        if (overflowIsolateCount > 0) {
          overflowIsolateCount--;
        } else if (validIsolateCount > 0) {
          overflowEmbeddingCount = 0;
          while (!top().isolate) stack.pop();
          stack.pop();
          validIsolateCount--;
        }
        const cur = top();
        levels[i] = cur.level;
        if (cur.override !== 'N') types[i] = cur.override;
        break;
      }
      case 'PDF': {
        levels[i] = top().level;
        if (overflowIsolateCount > 0) {
          // do nothing
        } else if (overflowEmbeddingCount > 0) {
          overflowEmbeddingCount--;
        } else if (!top().isolate && stack.length >= 2) {
          stack.pop();
        }
        break;
      }
      case 'B': {
        levels[i] = paragraphLevel;
        stack.length = 1;
        stack[0] = { level: paragraphLevel, override: 'N', isolate: false };
        overflowIsolateCount = 0;
        overflowEmbeddingCount = 0;
        validIsolateCount = 0;
        break;
      }
      case 'BN': {
        levels[i] = top().level;
        break;
      }
      default: {
        // X6: every other type.
        const cur = top();
        levels[i] = cur.level;
        if (cur.override !== 'N') types[i] = cur.override;
        break;
      }
    }
  }
  return levels;
}

// ─── X9: characters removed from further (W/N/I) processing ───────────────────────────────

const X9_REMOVED: ReadonlySet<Cls> = new Set(['RLE', 'LRE', 'RLO', 'LRO', 'PDF', 'BN']);

function survivingIndices(codeTypes: Cls[]): number[] {
  const kept: number[] = [];
  for (let i = 0; i < codeTypes.length; i++) if (!X9_REMOVED.has(codeTypes[i] as Cls)) kept.push(i);
  return kept;
}

// ─── BD7 + BD13: isolating run sequences ───────────────────────────────────────────────────

interface Sequence {
  /** Original (pre-X9) code-point indices covered by this sequence, in left-to-right order. */
  orig: number[];
  level: number;
  sos: 'L' | 'R';
  eos: 'L' | 'R';
}

function buildIsolatingRunSequences(
  kept: number[],
  levels: Uint8Array,
  codeTypes: Cls[],
  matchingPDI: (number | undefined)[],
  paragraphLevel: 0 | 1,
): Sequence[] {
  if (kept.length === 0) return [];

  // BD7: maximal same-level runs over `kept`, as [start, end) positions *within `kept`*.
  interface Run {
    start: number;
    end: number;
  }
  const runs: Run[] = [];
  {
    let i = 0;
    while (i < kept.length) {
      let j = i + 1;
      while (j < kept.length && levels[kept[j] as number] === levels[kept[i] as number]) j++;
      runs.push({ start: i, end: j });
      i = j;
    }
  }

  const posOfOrig = new Map<number, number>(); // original index -> position within `kept`
  kept.forEach((orig, pos) => posOfOrig.set(orig, pos));
  const runStartingAtPos = new Map<number, number>(); // `kept`-position -> run index
  runs.forEach((r, idx) => runStartingAtPos.set(r.start, idx));

  const sequences: Sequence[] = [];
  for (let r = 0; r < runs.length; r++) {
    const run = runs[r] as Run;
    const firstOrig = kept[run.start] as number;
    const firstType = codeTypes[firstOrig] as Cls;
    const startsSequence = firstType !== 'PDI' || matchingPDI[firstOrig] === undefined;
    if (!startsSequence) continue;

    const chain: Run[] = [run];
    let cur = run;
    for (;;) {
      const lastOrig = kept[cur.end - 1] as number;
      const lastType = codeTypes[lastOrig] as Cls;
      if (!ISOLATE_INITIATORS.has(lastType)) break;
      const pdiOrig = matchingPDI[lastOrig];
      if (pdiOrig === undefined) break;
      const pdiPos = posOfOrig.get(pdiOrig);
      if (pdiPos === undefined) break;
      const nextRunIdx = runStartingAtPos.get(pdiPos);
      if (nextRunIdx === undefined) break;
      const nextRun = runs[nextRunIdx] as Run;
      chain.push(nextRun);
      cur = nextRun;
    }

    const orig: number[] = [];
    for (const run2 of chain) for (let p = run2.start; p < run2.end; p++) orig.push(kept[p] as number);
    const seqLevel = levels[orig[0] as number] as number;

    const firstRun = chain[0] as Run;
    const precedingLevel = firstRun.start === 0 ? paragraphLevel : levels[kept[firstRun.start - 1] as number];
    const sosLevel = Math.max(seqLevel, precedingLevel as number);
    const sos: 'L' | 'R' = sosLevel % 2 === 0 ? 'L' : 'R';

    const lastRun = chain[chain.length - 1] as Run;
    const lastOrigOfSeq = kept[lastRun.end - 1] as number;
    const lastTypeOfSeq = codeTypes[lastOrigOfSeq] as Cls;
    const endsWithUnmatchedIsolateInitiator = ISOLATE_INITIATORS.has(lastTypeOfSeq) && matchingPDI[lastOrigOfSeq] === undefined;
    const succeedingLevel =
      endsWithUnmatchedIsolateInitiator || lastRun.end === kept.length ? paragraphLevel : levels[kept[lastRun.end] as number];
    const eosLevel = Math.max(seqLevel, succeedingLevel as number);
    const eos: 'L' | 'R' = eosLevel % 2 === 0 ? 'L' : 'R';

    sequences.push({ orig, level: seqLevel, sos, eos });
  }
  return sequences;
}

// ─── W1–W7 ──────────────────────────────────────────────────────────────────────────────────

function w1(t: Cls[], sos: 'L' | 'R'): void {
  for (let i = 0; i < t.length; i++) {
    if (t[i] !== 'NSM') continue;
    if (i === 0) {
      t[i] = sos;
      continue;
    }
    const prev = t[i - 1] as Cls;
    t[i] = prev === 'LRI' || prev === 'RLI' || prev === 'FSI' || prev === 'PDI' ? 'ON' : prev;
  }
}

function w2(t: Cls[], sos: 'L' | 'R'): void {
  let strong: Cls = sos;
  for (let i = 0; i < t.length; i++) {
    const c = t[i] as Cls;
    if (c === 'R' || c === 'L' || c === 'AL') strong = c;
    else if (c === 'EN' && strong === 'AL') t[i] = 'AN';
  }
}

function w3(t: Cls[]): void {
  for (let i = 0; i < t.length; i++) if (t[i] === 'AL') t[i] = 'R';
}

function w4(t: Cls[]): void {
  for (let i = 1; i < t.length - 1; i++) {
    const c = t[i];
    const before = t[i - 1];
    const after = t[i + 1];
    if (c === 'ES' && before === 'EN' && after === 'EN') t[i] = 'EN';
    else if (c === 'CS' && ((before === 'EN' && after === 'EN') || (before === 'AN' && after === 'AN'))) t[i] = before as Cls;
  }
}

function w5(t: Cls[]): void {
  let i = 0;
  while (i < t.length) {
    if (t[i] !== 'ET') {
      i++;
      continue;
    }
    let j = i;
    while (j < t.length && t[j] === 'ET') j++;
    const beforeIsEN = i > 0 && t[i - 1] === 'EN';
    const afterIsEN = j < t.length && t[j] === 'EN';
    if (beforeIsEN || afterIsEN) for (let k = i; k < j; k++) t[k] = 'EN';
    i = j;
  }
}

function w6(t: Cls[]): void {
  for (let i = 0; i < t.length; i++) if (t[i] === 'ES' || t[i] === 'ET' || t[i] === 'CS') t[i] = 'ON';
}

function w7(t: Cls[], sos: 'L' | 'R'): void {
  let strong: Cls = sos;
  for (let i = 0; i < t.length; i++) {
    const c = t[i] as Cls;
    if (c === 'R' || c === 'L') strong = c;
    else if (c === 'EN' && strong === 'L') t[i] = 'L';
  }
}

// ─── N0 / BD16: paired brackets ─────────────────────────────────────────────────────────────

const BD16_STACK_MAX = 63;

/** BD16's canonical-equivalence carve-out: U+2329/U+232A (angle brackets) match U+3008/U+3009. */
function canonicalizeBracket(cp: number): number {
  if (cp === 0x2329) return 0x3008;
  if (cp === 0x232a) return 0x3009;
  return cp;
}

/** N0's "within this scope, EN and AN are treated as R." Returns `undefined` for anything not strong. */
function n0EffectiveDir(t: Cls): 'L' | 'R' | undefined {
  if (t === 'L') return 'L';
  if (t === 'R' || t === 'EN' || t === 'AN') return 'R';
  return undefined;
}

function resolveBrackets(seqTypes: Cls[], seqCps: number[], level: number, sos: 'L' | 'R'): void {
  const eDir: 'L' | 'R' = level % 2 === 0 ? 'L' : 'R';
  const oDir: 'L' | 'R' = eDir === 'L' ? 'R' : 'L';

  // BD16: identify bracket pairs.
  const stack: { closeCp: number; pos: number }[] = [];
  const pairs: [number, number][] = [];
  let stackOverflowed = false;
  for (let i = 0; i < seqTypes.length && !stackOverflowed; i++) {
    if (seqTypes[i] !== 'ON') continue;
    const cp = seqCps[i] as number;
    const bi = exactIndex(BIDI_BRACKET_CODES, cp);
    if (bi < 0) continue;
    const isOpen = (BIDI_BRACKET_TYPES[bi] ?? 0) === 0;
    if (isOpen) {
      if (stack.length >= BD16_STACK_MAX) {
        stackOverflowed = true; // "stop processing BD16 for the remainder of the isolating run sequence"
        break;
      }
      stack.push({ closeCp: canonicalizeBracket(BIDI_BRACKET_PAIRED[bi] as number), pos: i });
    } else {
      const target = canonicalizeBracket(cp);
      for (let s = stack.length - 1; s >= 0; s--) {
        if ((stack[s] as { closeCp: number; pos: number }).closeCp === target) {
          pairs.push([(stack[s] as { closeCp: number; pos: number }).pos, i]);
          stack.length = s;
          break;
        }
      }
    }
  }
  pairs.sort((a, b) => a[0] - b[0]);

  for (const [openPos, closePos] of pairs) {
    let foundEDir = false;
    let foundODir = false;
    for (let k = openPos + 1; k < closePos; k++) {
      const eff = n0EffectiveDir(seqTypes[k] as Cls);
      if (eff === eDir) {
        foundEDir = true;
        break;
      }
      if (eff === oDir) foundODir = true;
    }
    if (foundEDir) {
      seqTypes[openPos] = eDir;
      seqTypes[closePos] = eDir;
    } else if (foundODir) {
      let context: 'L' | 'R' = sos;
      for (let k = openPos - 1; k >= 0; k--) {
        const eff = n0EffectiveDir(seqTypes[k] as Cls);
        if (eff !== undefined) {
          context = eff;
          break;
        }
      }
      const assign = context === oDir ? oDir : eDir;
      seqTypes[openPos] = assign;
      seqTypes[closePos] = assign;
    }
    // else: no strong type enclosed — leave both brackets neutral for N1/N2.
  }
}

// ─── N1–N2 ──────────────────────────────────────────────────────────────────────────────────

function isNI(t: Cls): boolean {
  return t === 'B' || t === 'S' || t === 'WS' || t === 'ON' || t === 'FSI' || t === 'LRI' || t === 'RLI' || t === 'PDI';
}

/** By this point (post W1–W7, N0) every non-NI type is L, R, EN or AN; EN/AN act as R (N1). */
function strongForN1(t: Cls): 'L' | 'R' {
  return t === 'L' ? 'L' : 'R';
}

/**
 * W1 restated for N0's sake (empirically required — see the task 8 report's "W1/N0
 * interaction" finding). W1 makes an NSM inherit its base character's type as a *snapshot*
 * at W1's own position in the rule order — before N0 has resolved any bracket the base
 * happens to be. `BidiCharacterTest.txt` lines 84–89 and 103/109/114 (a bracket pair whose
 * *closing* bracket is immediately followed, outside the pair, by an NSM at the very end of
 * the sequence) show the officially expected result treats the NSM as if it had inherited
 * the base's *final* resolved type instead: e.g. `0661 0028 0662 0029 0331` (AN, "(", AN,
 * ")", NSM) resolves the ")" to R via N0 (context lookback finds the leading AN), and the
 * conformance data resolves the trailing NSM to R too — not the L that a strict, order-only
 * reading of N1/N2 (an isolated NI run at the sequence's true end, `before`=R, `eos`=L for
 * an LTR paragraph, mismatched → N2's embedding-direction default, L) produces. Re-syncing
 * each original NSM position to its immediately preceding position's *final* (post-N0,
 * post-N1/N2) type — left to right, so a chain of NSMs propagates exactly as W1 itself
 * chains them — reproduces the official data exactly and is a no-op everywhere the base's
 * type never changed after W1 (i.e. every case that wasn't already failing).
 */
function resyncNonspacingMarks(seqTypes: Cls[], seqOrig: number[], codeTypes: Cls[]): void {
  for (let i = 1; i < seqTypes.length; i++) {
    if (codeTypes[seqOrig[i] as number] === 'NSM') seqTypes[i] = seqTypes[i - 1] as Cls;
  }
}

function resolveNeutrals(t: Cls[], sos: 'L' | 'R', eos: 'L' | 'R', level: number): void {
  const eDir: 'L' | 'R' = level % 2 === 0 ? 'L' : 'R';
  let i = 0;
  while (i < t.length) {
    if (!isNI(t[i] as Cls)) {
      i++;
      continue;
    }
    let j = i;
    while (j < t.length && isNI(t[j] as Cls)) j++;
    const before = i === 0 ? sos : strongForN1(t[i - 1] as Cls);
    const after = j === t.length ? eos : strongForN1(t[j] as Cls);
    const dir = before === after ? before : eDir;
    for (let k = i; k < j; k++) t[k] = dir;
    i = j;
  }
}

// ─── I1–I2 ──────────────────────────────────────────────────────────────────────────────────

function resolveImplicitLevels(t: Cls[], level: number): number[] {
  const out: number[] = new Array(t.length);
  const even = level % 2 === 0;
  for (let i = 0; i < t.length; i++) {
    const c = t[i] as Cls;
    if (even) out[i] = c === 'L' ? level : c === 'R' ? level + 1 : level + 2; // EN/AN
    else out[i] = c === 'R' ? level : level + 1; // L, EN, AN
  }
  return out;
}

// ─── L1 ─────────────────────────────────────────────────────────────────────────────────────

const L1_WS_OR_ISOLATE: ReadonlySet<Cls> = new Set(['WS', 'LRI', 'RLI', 'FSI', 'PDI']);

/**
 * L1, over the whole paragraph treated as one line (see header comment's scope note). Uses
 * the *original* Bidi_Class (`codeTypes`, never overwritten by X6/N0/etc.), per L1's own text.
 *
 * **X9-removed characters are transparent to "at the end of the line" / "before a
 * separator".** `BidiTest.txt` line 2476 (`LRE WS LRE; 3`, `@Levels: x 0 x`) is the case
 * that proves it: the trailing LRE is removed by X9, so the WS immediately before it *is*
 * "at the end of the line" once removed characters are looked through, and L1 resets it to
 * the paragraph level — even though, ignoring X9, it would look like an embedding is still
 * open around it. A naive backward scan that stops at the first non-WS/isolate character
 * (rather than skipping X9-removed ones and continuing) misses this and leaves the WS at its
 * embedded level; both scans below skip `X9_REMOVED` characters instead of stopping at them.
 */
function applyL1Reset(levels: Uint8Array, codeTypes: Cls[], paragraphLevel: 0 | 1): void {
  const n = levels.length;
  for (let i = 0; i < n; i++) {
    const c = codeTypes[i];
    if (c === 'S' || c === 'B') levels[i] = paragraphLevel;
  }
  let i = n - 1;
  while (i >= 0) {
    const c = codeTypes[i] as Cls;
    if (X9_REMOVED.has(c)) {
      i--;
      continue;
    }
    if (!L1_WS_OR_ISOLATE.has(c)) break;
    levels[i] = paragraphLevel;
    i--;
  }
  for (let k = 0; k < n; k++) {
    if (codeTypes[k] !== 'S' && codeTypes[k] !== 'B') continue;
    let j = k - 1;
    while (j >= 0) {
      const c = codeTypes[j] as Cls;
      if (X9_REMOVED.has(c)) {
        j--;
        continue;
      }
      if (!L1_WS_OR_ISOLATE.has(c)) break;
      levels[j] = paragraphLevel;
      j--;
    }
  }
}

// ─── Public API (task 8 brief's exact interfaces) ──────────────────────────────────────────

/** Fast-path guard classes: see header comment's proof. */
const EARLY_OUT_BLOCKERS: ReadonlySet<Cls> = new Set(['R', 'AL', 'AN', 'RLE', 'LRE', 'RLO', 'LRO', 'PDF', 'RLI', 'LRI', 'FSI', 'PDI']);

/**
 * UAX #9's full P/X/W/N/I/L pipeline (spec 02 §6.3), one entry per **code point** of `text`
 * (see header comment on indexing). `paragraphLevel` is `resolveParagraphLevel`'s result.
 */
export function bidiLevels(text: string, paragraphLevel: 0 | 1): Uint8Array {
  const cps = decode(text);
  const n = cps.length;
  const levels = new Uint8Array(n);
  if (n === 0) return levels;

  const codeTypes: Cls[] = new Array(n);
  let needsFullResolution = paragraphLevel === 1;
  for (let i = 0; i < n; i++) {
    const cls = classOf((cps[i] as CodePointAt).cp);
    codeTypes[i] = cls;
    if (EARLY_OUT_BLOCKERS.has(cls)) needsFullResolution = true;
  }
  if (!needsFullResolution) return levels; // proven all-zero — see header comment.

  const matchingPDI = computeMatchingPDI(codeTypes);
  const workingTypes = codeTypes.slice();
  const explicitLevels = computeExplicitLevels(codeTypes, workingTypes, paragraphLevel, matchingPDI);
  const kept = survivingIndices(codeTypes);
  const sequences = buildIsolatingRunSequences(kept, explicitLevels, codeTypes, matchingPDI, paragraphLevel);

  for (const seq of sequences) {
    const seqTypes = seq.orig.map((idx) => workingTypes[idx] as Cls);
    const seqCps = seq.orig.map((idx) => (cps[idx] as CodePointAt).cp);
    w1(seqTypes, seq.sos);
    w2(seqTypes, seq.sos);
    w3(seqTypes);
    w4(seqTypes);
    w5(seqTypes);
    w6(seqTypes);
    w7(seqTypes, seq.sos);
    resolveBrackets(seqTypes, seqCps, seq.level, seq.sos);
    resolveNeutrals(seqTypes, seq.sos, seq.eos, seq.level);
    resyncNonspacingMarks(seqTypes, seq.orig, codeTypes);
    const finalLevels = resolveImplicitLevels(seqTypes, seq.level);
    for (let k = 0; k < seq.orig.length; k++) explicitLevels[seq.orig[k] as number] = finalLevels[k] as number;
  }

  for (let i = 0; i < n; i++) levels[i] = explicitLevels[i] as number;
  applyL1Reset(levels, codeTypes, paragraphLevel);
  return levels;
}

/**
 * L2, over `[start, end)` of a `bidiLevels` result (or any levels array in the same
 * code-point indexing): reverse contiguous runs at or above each level, from the highest
 * level down to the lowest odd level. Task 8 brief's exact interface — see header comment's
 * scope note on why this is pure L2, not L1+L2.
 */
export function reorderVisual(levels: Uint8Array, start: number, end: number): number[] {
  const order: number[] = [];
  for (let i = start; i < end; i++) order.push(i);
  let maxLevel = 0;
  let minOdd = Number.POSITIVE_INFINITY;
  for (let i = start; i < end; i++) {
    const lv = levels[i] ?? 0;
    if (lv > maxLevel) maxLevel = lv;
    if (lv % 2 === 1 && lv < minOdd) minOdd = lv;
  }
  if (!Number.isFinite(minOdd)) return order;
  for (let lvl = maxLevel; lvl >= minOdd; lvl--) {
    let i = 0;
    while (i < order.length) {
      if ((levels[order[i] as number] ?? 0) >= lvl) {
        let j = i;
        while (j < order.length && (levels[order[j] as number] ?? 0) >= lvl) j++;
        let a = i;
        let b = j - 1;
        while (a < b) {
          const tmp = order[a];
          order[a] = order[b] as number;
          order[b] = tmp as number;
          a++;
          b--;
        }
        i = j;
      } else {
        i++;
      }
    }
  }
  return order;
}

/**
 * BD14/BD15's `Bidi_Mirroring_Glyph` (`BidiMirroring.txt`): the mirrored code point for `cp`,
 * or `cp` itself when it has none. Level-agnostic — spec 02 §6.3 applies this "at display-text
 * generation", i.e. the caller mirrors only characters whose *resolved* level is odd. Task 8
 * brief's exact interface.
 */
export function mirrorChar(cp: number): number {
  const idx = exactIndex(BIDI_MIRROR_CODES, cp);
  return idx < 0 ? cp : ((BIDI_MIRROR_MAPPED[idx] as number | undefined) ?? cp);
}
