/**
 * `ucd/LICENSES.md` (spec 02 §6): "Data whose provenance is not recorded is not shippable."
 * This mirrors `src/fonts/budget.test.ts`'s license cross-check for the bundled fonts —
 * including its lesson. That test's first two checks (fields present, every SHA present
 * *somewhere*) were shown to pass even with Caladea's license wrongly labeled Apache 2.0,
 * because "Apache License, Version 2.0" is itself a real string that can appear elsewhere in
 * the same file; only a check that resolves each specific artifact to *its* claimed record
 * and requires that record to match a *ground truth read from the artifact itself* caught it.
 *
 * So every check below resolves against something actually on disk, not a fixed expectation
 * that would keep passing after a source is silently added and forgotten:
 *  - the terms-of-use URL is read out of a committed UCD file's own header, not typed from
 *    memory;
 *  - each source file's SHA-256 is read out of its own generated output's header
 *    (`scripts/build-ucd.ts`'s `HEADER()`), not a copy that could drift from it;
 *  - each conformance file's SHA-256 is computed fresh from the committed `test/ucd/` bytes.
 * A new entry in `scripts/build-ucd.ts`'s `SOURCES` or `CONFORMANCE` maps, once regenerated,
 * produces a new file or a new embedded/actual SHA-256 that these tests require
 * `ucd/LICENSES.md` to already list — so an unrecorded addition fails here, not silently.
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '../..');
const LICENSES_PATH = join(ROOT, 'ucd/LICENSES.md');
const LICENSE_TEXT_PATH = join(ROOT, 'ucd/UNICODE-LICENSE.txt');
const GENERATED_DIR = join(ROOT, 'src/text/generated');
const CONFORMANCE_DIR = join(ROOT, 'test/ucd');

function sha256(buf: Buffer): string {
  return createHash('sha256').update(buf).digest('hex');
}

const licenses = readFileSync(LICENSES_PATH, 'utf8');

describe('ucd/LICENSES.md (spec 02 §6)', () => {
  it('names the Unicode Character Database, its pinned version, and a license', () => {
    for (const heading of ['License:', 'Version:', 'Source URL base:']) {
      expect(licenses, `ucd/LICENSES.md missing a '${heading}' field`).toContain(heading);
    }
    expect(licenses).toContain('16.0.0');
    expect(licenses).toMatch(/Unicode License v3/);
  });

  it('vendors the actual Unicode License v3 text (not a paraphrase)', () => {
    const text = readFileSync(LICENSE_TEXT_PATH, 'utf8');
    expect(text).toMatch(/UNICODE LICENSE V3/);
    expect(text).toMatch(/Unicode, Inc\./);
    // The operative grant, quoted, so a swapped-in different license would fail this line.
    expect(text).toMatch(/Permission is hereby granted, free of charge/);
  });

  it("ground-truths the terms-of-use pointer against a committed UCD file's own header", () => {
    // Every file scripts/build-ucd.ts fetches carries this line in its own header — the
    // data's own record of its license pointer, not a secondary source's claim about it.
    const graphemeTest = readFileSync(join(CONFORMANCE_DIR, 'GraphemeBreakTest.txt'), 'utf8');
    const m = /For terms of use and license, see (\S+)/.exec(graphemeTest);
    expect(m, "GraphemeBreakTest.txt's header no longer states a terms-of-use URL — re-verify the license record").not.toBeNull();
    expect(licenses, 'ucd/LICENSES.md does not cite the terms-of-use URL the data itself points to').toContain(m![1]!);
  });

  it("records every SOURCES file the generator emits, with the SHA-256 its own generated header carries", () => {
    const files = readdirSync(GENERATED_DIR).filter((f) => f.endsWith('.generated.ts'));
    expect(files.length).toBeGreaterThan(0);
    const HEADER_RE = /GENERATED by scripts\/build-ucd\.ts from (\S+) \(Unicode [\d.]+\) — do not edit\.\n\/\/ Source SHA-256: ([0-9a-f]{64})/;
    let checked = 0;
    for (const file of files) {
      const src = readFileSync(join(GENERATED_DIR, file), 'utf8');
      const m = HEADER_RE.exec(src);
      expect(m, `${file}: does not carry the expected GENERATED header`).not.toBeNull();
      const [, sourceFile, sha] = m!;
      expect(licenses, `ucd/LICENSES.md does not mention source file ${sourceFile}`).toContain(sourceFile!);
      expect(
        licenses,
        `ucd/LICENSES.md is missing SHA-256 ${sha} for source file ${sourceFile} (embedded in ${file}'s own header)`,
      ).toContain(sha!);
      checked++;
    }
    expect(checked).toBe(files.length);
  });

  it('records every conformance file committed under test/ucd/, with its actual on-disk SHA-256', () => {
    const files = readdirSync(CONFORMANCE_DIR).filter((f) => f.endsWith('.txt'));
    expect(files.length).toBeGreaterThan(0);
    for (const file of files) {
      const sha = sha256(readFileSync(join(CONFORMANCE_DIR, file)));
      expect(licenses, `ucd/LICENSES.md does not mention conformance file ${file}`).toContain(file);
      expect(
        licenses,
        `ucd/LICENSES.md is missing SHA-256 ${sha} for conformance file ${file} (its actual committed hash)`,
      ).toContain(sha);
    }
  });
});
