// GENERATED by scripts/build-ucd.ts — do not edit.
// Unicode Character Database version pin (spec 02 §36.1: "UCD version" is part of
// LAYOUT_ENGINE_VERSION's bump surface).
export const UNICODE_VERSION = '16.0.0';

import { lookupRangeValue } from './ucd-lookup.js';
import { GRAPHEME_BREAK_NAMES, GRAPHEME_BREAK_STARTS, GRAPHEME_BREAK_VALUES, type GraphemeBreakClass } from './generated/grapheme-break.generated.js';
import { LINE_BREAK_NAMES, LINE_BREAK_STARTS, LINE_BREAK_VALUES, type LineBreakClass } from './generated/line-break.generated.js';
import { BIDI_CLASS_NAMES, BIDI_CLASS_STARTS, BIDI_CLASS_VALUES, type BidiClass } from './generated/bidi-class.generated.js';
import { SCRIPT_NAMES, SCRIPT_STARTS, SCRIPT_VALUES, type ScriptCode } from './generated/script.generated.js';
import { GENERAL_CATEGORY_NAMES, GENERAL_CATEGORY_STARTS, GENERAL_CATEGORY_VALUES, type GeneralCategory } from './generated/general-category.generated.js';
import { WORD_BREAK_NAMES, WORD_BREAK_STARTS, WORD_BREAK_VALUES, type WordBreakClass } from './generated/word-break.generated.js';
import { SENTENCE_BREAK_NAMES, SENTENCE_BREAK_STARTS, SENTENCE_BREAK_VALUES, type SentenceBreakClass } from './generated/sentence-break.generated.js';
import { EAST_ASIAN_WIDTH_NAMES, EAST_ASIAN_WIDTH_STARTS, EAST_ASIAN_WIDTH_VALUES, type EastAsianWidth } from './generated/east-asian-width.generated.js';

export type { GraphemeBreakClass, LineBreakClass, BidiClass, ScriptCode, GeneralCategory, WordBreakClass, SentenceBreakClass, EastAsianWidth };

/** Unicode 16.0 Grapheme_Cluster_Break (spec 02 §6.1). */
export function graphemeBreakProperty(cp: number): GraphemeBreakClass {
  return GRAPHEME_BREAK_NAMES[lookupRangeValue(GRAPHEME_BREAK_STARTS, GRAPHEME_BREAK_VALUES, cp)] ?? 'Other';
}

/** Unicode 16.0 Line_Break (spec 02 §6.2). */
export function lineBreakClass(cp: number): LineBreakClass {
  return LINE_BREAK_NAMES[lookupRangeValue(LINE_BREAK_STARTS, LINE_BREAK_VALUES, cp)] ?? 'XX';
}

/** Unicode 16.0 Bidi_Class, derived (spec 02 §6.3). */
export function bidiClass(cp: number): BidiClass {
  return BIDI_CLASS_NAMES[lookupRangeValue(BIDI_CLASS_STARTS, BIDI_CLASS_VALUES, cp)] ?? 'L';
}

/** Unicode 16.0 Script. */
export function script(cp: number): ScriptCode {
  return SCRIPT_NAMES[lookupRangeValue(SCRIPT_STARTS, SCRIPT_VALUES, cp)] ?? 'Unknown';
}

/** Unicode 16.0 General_Category, derived. */
export function generalCategory(cp: number): GeneralCategory {
  return GENERAL_CATEGORY_NAMES[lookupRangeValue(GENERAL_CATEGORY_STARTS, GENERAL_CATEGORY_VALUES, cp)] ?? 'Cn';
}

/** Unicode 16.0 Word_Break (spec 02 §6.5). */
export function wordBreakProperty(cp: number): WordBreakClass {
  return WORD_BREAK_NAMES[lookupRangeValue(WORD_BREAK_STARTS, WORD_BREAK_VALUES, cp)] ?? 'Other';
}

/** Unicode 16.0 Sentence_Break (spec 02 §6.5). */
export function sentenceBreakProperty(cp: number): SentenceBreakClass {
  return SENTENCE_BREAK_NAMES[lookupRangeValue(SENTENCE_BREAK_STARTS, SENTENCE_BREAK_VALUES, cp)] ?? 'Other';
}

/** Unicode 16.0 East_Asian_Width (spec 02 §6.2, task 7). */
export function eastAsianWidth(cp: number): EastAsianWidth {
  return EAST_ASIAN_WIDTH_NAMES[lookupRangeValue(EAST_ASIAN_WIDTH_STARTS, EAST_ASIAN_WIDTH_VALUES, cp)] ?? 'N';
}
