/**
 * Spec 02 §21 (assignment), §21.3/§20.2 (the `counts` map) and §22.3/§23.2 (locked gaps and
 * provisional labels): walks a document once and decides, per element, whether it is numbered and
 * what `NumberLabel` it gets. Formatting (`{n…}`, `{count:<StyleId>}` etc) is a later concern
 * (Task 11's `renderTokenString`, fed by `TokenContext.number`) — this module only produces the
 * structured label and the `{count:<StyleId>}` input, never a formatted string.
 *
 * The whole walk operates over a single filtered, ordered element list ("visible"): every element
 * of `model.elements()` minus §9.2 hidden outline/note elements and minus the body of an omitted
 * scene (its heading — the `OMITTED` placeholder line — stays; spec 02 §23.3). Numbering,
 * resetAfterStyle triggers and `counts` all read document order off that one filtered list, so a
 * hidden or omitted-body element is uniformly invisible to every rule here, not just the one that
 * happens to be under test.
 */

import type { ElementId, StyleId } from '../ids/ids.js';
import type { DocumentModel } from '../read-model/open.js';
import type { ElementView } from '../read-model/views.js';
import type { NumberLabel, NumberingSpec } from '../schema/template.js';
import type { NumberMode, StyleRole } from '../schema/vocab.js';
import { compareLabels } from '../read-model/number-label.js';
import { styleChain, resolveStyle } from '../template/resolve.js';
import type { ProductionJSON } from '../schema/document.js';
import { generateBetween } from './modes.js';

// ─── Public shapes (task 14 brief's exact signature) ───────────────────────────────────────────

export interface AssignNumbersOptions {
  // Reserved for a future caller (e.g. an incremental/partial recompute). Nothing in M2 reads a
  // field here yet; the parameter exists so the signature never has to change shape later.
}

export interface AssignedNumber {
  readonly label: NumberLabel;
  /**
   * True only for a label generated by §22.3 to fill a gap in a locked sequence (§23.2) — it is
   * not yet a permanent stored label (that happens on Relock, a later task) and the editor gutter
   * is expected to display it differently. Every other label (unlocked auto, unlocked manual,
   * locked-and-stored) is `false`.
   */
  readonly provisional: boolean;
  /**
   * True only when `provisional` is true AND the label came from §22.3 step 4's last-resort
   * prefix fallback (`generateBetween`'s own `gapExhausted` flag), rather than steps 2/3's
   * ordinary "strictly between P and R" generation. Spec 02 §22.3/§22.4: a step-4 label is not
   * guaranteed to sort between its neighbours (the `A10A` worked example sorts *before* `P`) and
   * carries diagnostic `numberGapExhausted` "so the UI can suggest Renumber" — a caller needs to
   * tell that apart from an ordinary, fully-ordered provisional label. Always `false` when
   * `provisional` is `false`.
   */
  readonly gapExhausted: boolean;
}

export interface AssignNumbersResult {
  labels: Map<ElementId, AssignedNumber>;
  counts: Map<ElementId, ReadonlyMap<StyleId, number>>;
}

/**
 * Spec 02 §22.3's refusal, surfaced as a typed, documented error rather than the bare `RangeError`
 * `generateBetween` throws (§22.3's own prose: `AB2`/`BA2` have no step 4, so once `R` already
 * carries a minimal prefix nothing can be generated that sorts between a locked `P` and `R`).
 * `assignNumbers` does not swallow this into a fabricated label or a silently-shorter result — the
 * spec is explicit that either would corrupt scene order in a locked production draft. It also
 * does not let the underlying `RangeError` escape unannotated: this error carries which style,
 * mode and elements the caller needs to resolve the refusal (Relock or Renumber), matching §22.3's
 * "the relock UI must prevent it rather than handle a partial result."
 */
export class NumberGapExhaustedError extends Error {
  readonly styleId: StyleId;
  readonly mode: NumberMode;
  readonly previous: NumberLabel | null;
  readonly next: NumberLabel | null;
  readonly elementIds: readonly ElementId[];

  constructor(opts: {
    styleId: StyleId;
    mode: NumberMode;
    previous: NumberLabel | null;
    next: NumberLabel | null;
    elementIds: readonly ElementId[];
    cause: unknown;
  }) {
    super(
      `assignNumbers: locked style '${opts.styleId}' (${opts.mode}) has no structural room for ` +
        `${opts.elementIds.length} unstored element(s) between its stored neighbours — Relock or ` +
        'Renumber before inserting here (spec 02 §22.3).',
      { cause: opts.cause },
    );
    this.name = 'NumberGapExhaustedError';
    this.styleId = opts.styleId;
    this.mode = opts.mode;
    this.previous = opts.previous;
    this.next = opts.next;
    this.elementIds = opts.elementIds;
  }
}

/**
 * Guards against a corrupted or hand-edited locked sequence: a stored, locked `num.label` whose
 * structural `base`/`prefix`/`suffix` does not sort strictly after the previous accepted locked
 * label in document order. `compareLabels`/`generateBetween` never read `.custom` (spec 02 §23.1's
 * "the structured base/prefix/suffix fields still carry the label's position"), so a locked
 * element whose display was blanked out (`custom: ''`) but whose structural position was never
 * updated to match — or any other out-of-order stored label — would otherwise be silently trusted
 * as the next gap-fill anchor, producing a provisional label that sorts *before* an earlier locked
 * one with no error or diagnostic. `assignNumbers` rejects the anchor instead: this is exactly the
 * class of silent-corruption failure spec 02 §22.3 says the whole section exists to prevent.
 */
export class LockedLabelOutOfOrderError extends Error {
  readonly styleId: StyleId;
  readonly mode: NumberMode;
  readonly elementId: ElementId;
  readonly previous: NumberLabel;
  readonly stored: NumberLabel;

  constructor(opts: { styleId: StyleId; mode: NumberMode; elementId: ElementId; previous: NumberLabel; stored: NumberLabel }) {
    super(
      `assignNumbers: locked style '${opts.styleId}' has a stored label on element '${opts.elementId}' that does ` +
        `not sort after its predecessor under ${opts.mode} — the locked sequence is out of order (a non-` +
        'representative anchor, e.g. a blanked custom label whose structural position was never updated) and ' +
        'cannot be trusted to generate gap-fill labels from (spec 02 §22.3).',
    );
    this.name = 'LockedLabelOutOfOrderError';
    this.styleId = opts.styleId;
    this.mode = opts.mode;
    this.elementId = opts.elementId;
    this.previous = opts.previous;
    this.stored = opts.stored;
  }
}

// ─── Style-config lookups ───────────────────────────────────────────────────────────────────────

type StyleSource = Parameters<typeof resolveStyle>[0];

/**
 * Spec 02 §21.1: `counter: 'base'` "shares the counter of the nearest ancestor style (via
 * `basedOn`) whose rule has `counter: 'own'`". A style's own resolved `numbering` is a single
 * inherited unit (spec 01 §3.4.2 — `resolveStyle` inherits the whole `NumberingSpec` object, not
 * per-field), so `counter: 'base'` only ever shows up when a style declares its OWN `numbering`
 * object explicitly (different format/position, same sequence). Walk `styleId`'s `basedOn` chain
 * (leaf-first, so `chain[0]` is `styleId` itself) and return the first ancestor whose *resolved*
 * numbering is `counter: 'own'`. No ancestor declaring `'own'` is a misconfigured template; fall
 * back to `styleId` itself rather than looping forever or throwing on a template a user authored.
 */
function counterOwnerStyleId(template: StyleSource, styleId: StyleId): StyleId {
  const own = resolveStyle(template, styleId).numbering;
  if (!own || own.counter === 'own') return styleId;
  const chain = styleChain(template.styles, styleId);
  for (let i = 1; i < chain.length; i += 1) {
    const ancestorId = chain[i]!.id;
    const ancestorNumbering = resolveStyle(template, ancestorId).numbering;
    if (ancestorNumbering && ancestorNumbering.counter === 'own') return ancestorId;
  }
  return styleId;
}

/** Spec 02 §21.1: a style is locked when its id is in `production.lockedStyles`, or it is the scene
 * heading style and `production.scenesLocked`. Lock state is tracked per counter-owner style: two
 * styles sharing one counter (`counter: 'base'`) are locked or unlocked together, keyed by the
 * owner — Lock Numbers/Unlock (§23.1) operate on the sequence as a whole, and a counter cannot be
 * half auto-numbered, half stored-and-generated without an ordering that no longer means anything.
 */
function isStyleLocked(styleId: StyleId, role: StyleRole, production: ProductionJSON): boolean {
  if (production.lockedStyles.includes(styleId)) return true;
  return role === 'sceneHeading' && production.scenesLocked;
}

// ─── §9.2 / §23.3 visibility ────────────────────────────────────────────────────────────────────

/**
 * Spec 02 §9.2: "`outline`-role elements … and `note`-role elements are laid out only when
 * visible: hidden when the style has `hiddenInScript` and `settings.outlineHidden` is true."
 * Spec 02 §23.3: an omitted scene collapses to one line in the scene-heading style (the heading
 * element itself, still numbered — it IS the `OMITTED` placeholder); every other element up to the
 * next scene boundary is excluded, content preserved but not laid out.
 */
function computeExcludedIds(model: DocumentModel): ReadonlySet<ElementId> {
  const excluded = new Set<ElementId>();
  const template = model.template();
  const settings = model.settings();
  for (const el of model.elements()) {
    if (el.role !== 'outline' && el.role !== 'note') continue;
    const resolved = resolveStyle(template, el.style);
    if (resolved.hiddenInScript && settings.outlineHidden) excluded.add(el.id);
  }
  for (const scene of model.scenes()) {
    if (!scene.omitted) continue;
    // elementIds[0] is the scene-heading element itself (structure.ts always seeds `members`
    // with the heading first) — the OMITTED placeholder line, which stays numbered.
    for (const id of scene.elementIds.slice(1)) excluded.add(id);
  }
  return excluded;
}

// ─── Numbered-element predicate ────────────────────────────────────────────────────────────────

/** Spec 02 §21.2: "Parentheticals are never numbered even if configured" — a hard role guard, not
 * merely the default `numbering.enabled` — checked before the style's own config. */
function isNumberedElement(template: StyleSource, el: ElementView): boolean {
  if (el.role === 'parenthetical') return false;
  const numbering = resolveStyle(template, el.style).numbering;
  return numbering !== null && numbering.enabled;
}

// ─── Unlocked group (§21.2) ─────────────────────────────────────────────────────────────────────

function assignUnlockedGroup(
  visible: readonly ElementView[],
  template: StyleSource,
  owner: StyleId,
  ownerOf: (styleId: StyleId) => StyleId,
  numbering: NumberingSpec,
  labels: Map<ElementId, AssignedNumber>,
): void {
  let next = numbering.start;
  let consumedSinceReset = 0;

  const bumpConsumed = (): void => {
    consumedSinceReset += 1;
    if (numbering.resetEvery > 0 && consumedSinceReset >= numbering.resetEvery) {
      next = numbering.start;
      consumedSinceReset = 0;
    }
  };

  for (const el of visible) {
    if (numbering.resetAfterStyle !== null && el.style === numbering.resetAfterStyle) {
      next = numbering.start;
      consumedSinceReset = 0;
    }
    if (!isNumberedElement(template, el) || ownerOf(el.style) !== owner) continue;

    const manual = el.num !== null && el.num.locked === false && el.num.manual === true;
    if (manual) {
      const stored = el.num!.label;
      if (stored.custom === '') {
        // §21.2: "A manual label with custom: '' means unnumbered … and consumes no number" —
        // `next` is left exactly as it was; the following auto element gets what this one would
        // have gotten had it never existed.
        continue;
      }
      labels.set(el.id, { label: stored, provisional: false, gapExhausted: false });
      if (stored.custom === undefined) {
        // Non-custom manual: "Subsequent unlocked elements continue from label.base + 1."
        next = stored.base + 1;
      } else {
        // Non-blank custom: "…or from the previous sequential value + 1 when the label is
        // custom" — the free-text override doesn't carry a numeric position, so the auto
        // sequence just keeps moving as though this element had taken the next auto value.
        next += 1;
      }
      bumpConsumed();
      continue;
    }

    labels.set(el.id, { label: { base: next, prefix: [], suffix: [] }, provisional: false, gapExhausted: false });
    next += 1;
    bumpConsumed();
  }
}

// ─── Locked group (§22.3 / §23.2) ──────────────────────────────────────────────────────────────

function assignLockedGroup(
  visible: readonly ElementView[],
  template: StyleSource,
  owner: StyleId,
  ownerOf: (styleId: StyleId) => StyleId,
  numbering: NumberingSpec,
  labels: Map<ElementId, AssignedNumber>,
): void {
  let previous: NumberLabel | null = null;
  let pending: ElementId[] = [];

  const flush = (nextStored: NumberLabel | null): void => {
    if (pending.length === 0) return;
    let result: { labels: NumberLabel[]; gapExhausted: boolean };
    try {
      result = generateBetween(previous, nextStored, pending.length, numbering.suffixMode, numbering.skipIO);
    } catch (cause) {
      // Only wrap §22.3's genuine "no structural room" refusal — anything else `generateBetween`
      // throws (e.g. `modes.ts`'s own data-corruption guard for a malformed stored prefix segment)
      // is a different failure and must not be relabeled as a suggestion to Renumber.
      if (cause instanceof RangeError && cause.message.includes('no structural room')) {
        throw new NumberGapExhaustedError({
          styleId: owner, mode: numbering.suffixMode, previous, next: nextStored, elementIds: [...pending], cause,
        });
      }
      throw cause;
    }
    for (let i = 0; i < pending.length; i += 1) {
      labels.set(pending[i]!, { label: result.labels[i]!, provisional: true, gapExhausted: result.gapExhausted });
    }
    pending = [];
  };

  for (const el of visible) {
    if (!isNumberedElement(template, el) || ownerOf(el.style) !== owner) continue;
    const stored = el.num !== null && el.num.locked === true ? el.num.label : null;
    if (stored === null) {
      pending.push(el.id);
      continue;
    }
    // A locked, stored label must sort strictly after the previous accepted anchor — see
    // `LockedLabelOutOfOrderError`. Checked before `flush` so a non-representative anchor is
    // rejected outright rather than handed to `generateBetween` as a `P`/`R` pair that no longer
    // reflects document order (which can otherwise "succeed" via step 4's unconstrained fallback
    // and silently produce a label that sorts before an earlier locked one).
    if (previous !== null && compareLabels(stored, previous, numbering.suffixMode) <= 0) {
      throw new LockedLabelOutOfOrderError({ styleId: owner, mode: numbering.suffixMode, elementId: el.id, previous, stored });
    }
    flush(stored);
    // §21.2's custom:'' carve-out applies here too: the element is unnumbered (no display), but
    // its structural base/prefix/suffix (the fields `compareLabels`/`generateBetween` read —
    // `custom` never participates there) still marks its true locked position, so a later gap
    // still generates correctly relative to it.
    if (stored.custom !== '') labels.set(el.id, { label: stored, provisional: false, gapExhausted: false });
    previous = stored;
  }
  flush(null);
}

// ─── counts (§20.2 `{count:<StyleId>}`, §21.3) ─────────────────────────────────────────────────

/**
 * Spec 02 §20.2/§21.3: "Number of elements of `<StyleId>` from this element up to the next element
 * of the same numbered style." Scoped to exactly the elements that got a label (an element with no
 * label has no `TokenContext.number` to attach a `counts` entry to) — computed once, off the same
 * `visible` list the assignment walk already built, per the task's contract with Task 25.
 */
function computeCounts(
  visible: readonly ElementView[],
  labels: ReadonlyMap<ElementId, AssignedNumber>,
): Map<ElementId, ReadonlyMap<StyleId, number>> {
  const n = visible.length;
  const nextSameStyleIndex = new Array<number>(n);
  const lastIndexForStyle = new Map<StyleId, number>();
  for (let i = n - 1; i >= 0; i -= 1) {
    const style = visible[i]!.style;
    nextSameStyleIndex[i] = lastIndexForStyle.get(style) ?? n;
    lastIndexForStyle.set(style, i);
  }
  const indexOf = new Map<ElementId, number>();
  visible.forEach((el, i) => indexOf.set(el.id, i));

  const counts = new Map<ElementId, ReadonlyMap<StyleId, number>>();
  for (const id of labels.keys()) {
    const i = indexOf.get(id);
    if (i === undefined) continue; // every labeled id came from `visible`; defensive only
    const end = nextSameStyleIndex[i]!;
    const tally = new Map<StyleId, number>();
    for (let j = i; j < end; j += 1) {
      const style = visible[j]!.style;
      tally.set(style, (tally.get(style) ?? 0) + 1);
    }
    counts.set(id, tally);
  }
  return counts;
}

// ─── Entry point ────────────────────────────────────────────────────────────────────────────────

export function assignNumbers(model: DocumentModel, _opts: AssignNumbersOptions = {}): AssignNumbersResult {
  const template = model.template();
  const production = model.productionState();
  const excluded = computeExcludedIds(model);
  const visible = model.elements().filter((el) => !excluded.has(el.id));

  const ownerCache = new Map<StyleId, StyleId>();
  const ownerOf = (styleId: StyleId): StyleId => {
    let owner = ownerCache.get(styleId);
    if (owner === undefined) {
      owner = counterOwnerStyleId(template, styleId);
      ownerCache.set(styleId, owner);
    }
    return owner;
  };

  const groupOwners: StyleId[] = [];
  const seenOwners = new Set<StyleId>();
  for (const el of visible) {
    if (!isNumberedElement(template, el)) continue;
    const owner = ownerOf(el.style);
    if (!seenOwners.has(owner)) {
      seenOwners.add(owner);
      groupOwners.push(owner);
    }
  }

  const labels = new Map<ElementId, AssignedNumber>();
  for (const owner of groupOwners) {
    const ownerResolved = resolveStyle(template, owner);
    const numbering = ownerResolved.numbering;
    if (!numbering) continue; // defensive; a group only exists because a member was numbered
    if (isStyleLocked(owner, ownerResolved.role, production)) {
      assignLockedGroup(visible, template, owner, ownerOf, numbering, labels);
    } else {
      assignUnlockedGroup(visible, template, owner, ownerOf, numbering, labels);
    }
  }

  const counts = computeCounts(visible, labels);
  return { labels, counts };
}
