// Font metrics generator (spec 02 §4.1). Bun script; reads every font binary under
// `fonts/src/`, encodes one `.fwm` table per face and regenerates the `FACES` registry.
// Output under `src/fonts/generated/` is committed; CI regenerates and fails on any
// difference, so the committed tables always match the shipped binaries' SHA-256.
import { createHash } from 'node:crypto';
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { gzipSync } from 'node:zlib';
import * as fontkit from 'fontkit';
import { encodeFwm, type FwmRange } from '../src/fonts/fwm.js';

const SRC = 'fonts/src';
const OUT = 'src/fonts/generated';

/** `post.isFixedPitch` is parsed by fontkit at runtime but not declared by @types/fontkit. */
function isFixedPitch(font: fontkit.Font): boolean {
  const post = (font as unknown as { post?: { isFixedPitch?: number } }).post;
  return post?.isFixedPitch !== undefined && post.isFixedPitch !== 0;
}

/** Collapse consecutive code points sharing an advance into uniform ranges. */
function buildRanges(font: fontkit.Font): { ranges: FwmRange[] } {
  const points: { cp: number; advance: number }[] = [];
  for (const cp of font.characterSet) {
    try {
      points.push({ cp, advance: font.glyphForCodePoint(cp).advanceWidth });
    } catch {
      /* unmapped */
    }
  }
  points.sort((a, b) => a.cp - b.cp);
  // Ranges only; `defaultAdvance` is read from .notdef by the caller, not inferred here.
  const ranges: FwmRange[] = [];
  let i = 0;
  while (i < points.length) {
    let j = i;
    // Extend while code points are consecutive.
    while (j + 1 < points.length && points[j + 1]!.cp === points[j]!.cp + 1) j += 1;
    const slice = points.slice(i, j + 1);
    const first = slice[0]!.advance;
    const uniform = slice.every((p) => p.advance === first);
    ranges.push(
      uniform
        ? { start: slice[0]!.cp, length: slice.length, mode: 'uniform', advance: first }
        : { start: slice[0]!.cp, length: slice.length, mode: 'explicit', advances: slice.map((p) => p.advance) },
    );
    i = j + 1;
  }
  return { ranges };
}

/**
 * `<family-slug>:<style>` per spec 02 §4.3 — the id every other module uses.
 * Derived from the font's own name table, never from the file name, so a
 * re-downloaded binary with a different file name keeps its id.
 */
function faceIdOf(font: fontkit.Font): { faceId: string; family: string; style: string } {
  const family = font.familyName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
  const bold = /bold|black|heavy/i.test(font.subfamilyName);
  const italic = /italic|oblique/i.test(font.subfamilyName) || font.italicAngle !== 0;
  const style = bold && italic ? 'bolditalic' : bold ? 'bold' : italic ? 'italic' : 'regular';
  return { faceId: `${family}:${style}`, family, style };
}

mkdirSync(OUT, { recursive: true });
const entries: string[] = [];
for (const file of readdirSync(SRC).filter((f) => /\.(ttf|otf)$/i.test(f)).sort()) {
  const bytes = readFileSync(join(SRC, file));
  const font = fontkit.create(bytes) as fontkit.Font;
  const sha = createHash('sha256').update(bytes).digest('hex');
  const { ranges } = buildRanges(font);
  const { faceId, family, style } = faceIdOf(font);
  // .notdef is glyph 0; its advance is the spec §4.2 `defaultAdvance`, i.e. what
  // `advance(cp)` answers for an uncovered code point. NOT the modal advance.
  const defaultAdvance = font.getGlyph(0).advanceWidth;
  // The font's own declaration, not a heuristic over the ranges: a single
  // zero-advance combining glyph would make an "every range uniform" test lie.
  const monospace = isFixedPitch(font);
  const classification: 'mono' | 'serif' | 'sans' = monospace
    ? 'mono'
    : /serif/i.test(family) && !/sans/i.test(family)
      ? 'serif'
      : 'sans';
  const fwm = encodeFwm({
    faceId,
    unitsPerEm: font.unitsPerEm,
    ascender: font.ascent,
    descender: font.descent,
    lineGap: font.lineGap,
    capHeight: font.capHeight,
    xHeight: font.xHeight,
    underlinePosition: font.underlinePosition,
    underlineThickness: font.underlineThickness,
    strikeoutPosition: Math.round(font.capHeight / 2),
    strikeoutThickness: font.underlineThickness,
    italicAngle: font.italicAngle,
    monospace,
    requiresShaping: false,
    defaultAdvance,
    sourceSha256: sha,
    ranges,
    kernPairs: [], // proportional faces add kerning in Task 4
  });
  const moduleName = faceId.replace(':', '-'); // 'courier-prime-regular.fwm.ts'
  writeFileSync(
    join(OUT, `${moduleName}.fwm.ts`),
    `// GENERATED by scripts/build-font-metrics.ts — do not edit.\n` +
      `export const bytes = new Uint8Array([${fwm.join(',')}]);\n` +
      `export const sourceSha256 = '${sha}';\n`,
  );
  entries.push(
    `  { faceId: '${faceId}', family: '${family}', style: '${style}', classification: '${classification}', ` +
      `file: '${file}', sha256: '${sha}', unitsPerEm: ${font.unitsPerEm}, monospace: ${monospace}, ` +
      `requiresShaping: false, coverage: ${ranges.length} },`,
  );
  console.log(`${faceId}: ${ranges.length} ranges, ${fwm.byteLength} bytes, gz ${gzipSync(fwm).byteLength}`);
}
writeFileSync(
  join(OUT, 'registry.generated.ts'),
  `// GENERATED by scripts/build-font-metrics.ts — do not edit.\nexport const FACES = [\n${entries.join('\n')}\n] as const;\n`,
);
