import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { camelKey } from '../src/templates/role-table.js';
import { osfTemplateToJSON } from '../src/templates/generator/osf.js';
import { BUILTIN_SOURCES } from '../src/templates/generator/sources.js';
import { TemplateJSON } from '../src/schema/template.js';
import { validateTemplate } from '../src/template/validate.js';

const dir = resolve(process.env.FADEWRIGHT_TEMPLATES_DIR ?? '../screenwriter_plans/research/templates');
const out = resolve('src/templates/builtin/generated');
mkdirSync(out, { recursive: true });

const written: string[] = [];
for (const source of BUILTIN_SOURCES) {
  const xml = readFileSync(join(dir, source.file, 'document.xml'), 'utf8');
  const template = TemplateJSON.parse(osfTemplateToJSON(xml, source));
  const issues = validateTemplate(template);
  if (issues.length > 0) throw new Error(`${source.key}: ${JSON.stringify(issues)}`);
  const name = camelKey(source.key);
  writeFileSync(
    join(out, `${source.key}.ts`),
    `// GENERATED by scripts/generate-builtin-templates.ts from "${source.file}". Do not edit.\n` +
      `import type { TemplateJSON } from '../../../schema/template.js';\n\n` +
      `export const ${name} = ${JSON.stringify(template, null, 2)} as unknown as TemplateJSON;\n`,
  );
  written.push(name);
}

writeFileSync(
  join(out, 'index.ts'),
  '// GENERATED by scripts/generate-builtin-templates.ts. Do not edit.\n' +
    "import type { TemplateJSON } from '../../../schema/template.js';\n" +
    BUILTIN_SOURCES.map((s) => `import { ${camelKey(s.key)} } from './${s.key}.js';`).join('\n') +
    '\n\nexport const GENERATED_TEMPLATES: Readonly<Record<string, TemplateJSON>> = {\n' +
    BUILTIN_SOURCES.map((s) => `  '${s.key}': ${camelKey(s.key)},`).join('\n') +
    '\n};\n',
);
console.log(`wrote ${written.length} templates to ${out}`);
